"""remove_face_img_from_gift_and_superchat

Revision ID: e27014378950
Revises: 
Create Date: 2026-01-31 21:33:26.839448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e27014378950'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('face_img', sa.String(length=512), nullable=True),
    sa.Column('sessdata', sa.String(length=512), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('danmu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('privilege_name', sa.String(length=64), nullable=False),
    sa.Column('identity', sa.String(length=64), nullable=False),
    sa.Column('face_img', sa.String(length=255), nullable=True),
    sa.Column('dm_text', sa.String(length=255), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_danmu_room_id'), 'danmu', ['room_id'], unique=False)
    op.create_table('gift',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('privilege_name', sa.String(length=64), nullable=False),
    sa.Column('identity', sa.String(length=64), nullable=False),
    sa.Column('gift_name', sa.String(length=255), nullable=False),
    sa.Column('gift_num', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_room_id'), 'gift', ['room_id'], unique=False)
    op.create_table('gift_info_room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('coin_type', sa.String(length=64), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('host', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_room_id'), 'rooms', ['room_id'], unique=False)
    op.create_table('superchat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('privilege_name', sa.String(length=64), nullable=False),
    sa.Column('identity', sa.String(length=64), nullable=False),
    sa.Column('sc_text', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_superchat_room_id'), 'superchat', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_superchat_room_id'), table_name='superchat')
    op.drop_table('superchat')
    op.drop_index(op.f('ix_rooms_room_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_table('gift_info_room')
    op.drop_index(op.f('ix_gift_room_id'), table_name='gift')
    op.drop_table('gift')
    op.drop_index(op.f('ix_danmu_room_id'), table_name='danmu')
    op.drop_table('danmu')
    op.drop_table('auths')
    # ### end Alembic commands ###
